# Generated by Django 5.0.1 on 2024-01-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
